import { createHash } from "node:crypto";
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import ts from "typescript";

const root = resolve(import.meta.dirname, "..");
const dist = resolve(root, "dist");
const hash = createHash("sha256").update("pi-dynamic-workflows:compiled-generation-url-v1\0");
// The runtime imports this manifest. Version-only updates must get fresh JSON
// URLs too; otherwise Node could keep the previous package version cached.
const manifest = readFileSync(resolve(root, "package.json"));
hash.update(`package.json:${manifest.length}:`).update(manifest);
// Hash the fresh tsc output BEFORE URL stamping: no identity, Git state,
// timestamp, or self-referential digest enters the input.
const modules = readdirSync(dist)
  .filter((name) => name.endsWith(".js") && name !== "runtime-build.js")
  .sort();
for (const name of modules) {
  const bytes = readFileSync(resolve(dist, name));
  hash.update(`${name.length}:${name}:${bytes.length}:`).update(bytes);
}
const identity = `sha256:${hash.digest("hex")}`;
// Native ESM caches by URL, including the query. Every internal dependency
// edge must carry the SAME build query, not just the frontend or identity
// module. Otherwise independently cached producers can be relabeled as new.
for (const name of modules) {
  const path = resolve(dist, name);
  const text = readFileSync(path, "utf8");
  const source = ts.createSourceFile(name, text, ts.ScriptTarget.Latest, true, ts.ScriptKind.JS);
  const replacements: Array<{ start: number; end: number; value: string }> = [];
  const visit = (node: ts.Node) => {
    let specifier: ts.Node | undefined;
    if (ts.isImportDeclaration(node) || ts.isExportDeclaration(node)) specifier = node.moduleSpecifier;
    else if (ts.isCallExpression(node) && node.expression.kind === ts.SyntaxKind.ImportKeyword)
      specifier = node.arguments[0];
    if (specifier && ts.isStringLiteral(specifier) && /^\.\.?\/.*\.(js|json)$/.test(specifier.text)) {
      replacements.push({
        start: specifier.getStart(source),
        end: specifier.getEnd(),
        value: JSON.stringify(`${specifier.text}?workflowBuild=${identity}`),
      });
    }
    ts.forEachChild(node, visit);
  };
  visit(source);
  let stamped = text;
  for (const { start, end, value } of replacements.sort((a, b) => b.start - a.start))
    stamped = stamped.slice(0, start) + value + stamped.slice(end);
  writeFileSync(path, stamped);
}
writeFileSync(
  resolve(dist, "runtime-build.js"),
  `// Generated by stamp-runtime-build.ts; captured when this graph is loaded.\nexport const WORKFLOW_RUNTIME_BUILD_IDENTITY = ${JSON.stringify(identity)};\n`,
);
const frontend = resolve(root, "extensions/workflow.ts");
writeFileSync(
  frontend,
  readFileSync(frontend, "utf8")
    .replace(/const expectedBuildIdentity = "[^"]*";/, `const expectedBuildIdentity = "${identity}";`)
    .replace(
      /import\(\s*"\.\.\/dist\/pi-extension\.js(?:\?workflowBuild=[^"]*)?"\s*\)/,
      `import(\n  "../dist/pi-extension.js?workflowBuild=${identity}"\n)`,
    ),
);
